### ISSUE TITLE
Add automatization for importing the  docs

### ISSUE THREAD

**Issue by RaduNichita** [bemanproject/website#51]
We should find a way to sync documentation from `https://github.com/bemanproject/beman/tree/main/docs` and the `docs/` folder.

Possible ideas:

- Having a script that will run using a Github bot and make PR with the latest changes
- Having a script that we will run manually periodically and will submit the PR manually
- Put all the documentaion in one place and avoid doing the sync

**Comment by neatudarius** [comment]
For docs sync automatization I propose:
- Simplification and uniformization for syntax used in actual docs for beman/ - https://github.com/bemanproject/beman/pull/154
- Create a script inside the website repo used to pull, patch and generate static docs on the website - https://github.com/bemanproject/website/pull/95

Example of generate docs when running the script - https://github.com/bemanproject/website/pull/96.


@JeffGarland , can you review all 3 PRs?

**Comment by JeffGarland** [comment]
on it

**Comment by JeffGarland** [comment]
done

**Comment by neatudarius** [comment]
> done

 https://github.com/bemanproject/beman/pull/154 - @JeffGarland  how about this one? I think you forgot to press a button.

**Comment by neatudarius** [comment]
Implemented initial docs import automation with 2 triggers (check - https://github.com/bemanproject/website/blob/main/.github/workflows/sync-docs.yml)
1. manual trigger (`Actions` -> Select `Auto-sync Beman Docs` -> `Run workflow` -> Select `main`)
2. time-based (weekly) run

Here is a sample of manual automation:
- Action: https://github.com/bemanproject/website/actions/runs/23771792326

- Generated PR: https://github.com/bemanproject/website/pull/152

<img width="1494" height="754" alt="Image" src="https://github.com/user-attachments/assets/4d01889f-0e2d-4cca-a6c5-6246a2c05a16" />

- Generated PR preview: https://deploy-preview-152--bemanproject.netlify.app/

- Generated email notification

<img width="918" height="735" alt="Image" src="https://github.com/user-attachments/assets/935297b1-9d36-4bae-bd48-e4fb42ce4a7e" />
